[project]
name = "phidata"
version = "2.0.0.dev10"
description = "A toolkit for building applications using OSS"
requires-python = ">=3.7"
readme = "README.md"
authors = [
  {name = "Ashpreet Bedi", email = "ashpreet@phidata.com"}
]

dependencies = [
  "aiohttp",
  "boto3",
  "docker",
  "gitpython",
  "kubernetes",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
  "pyyaml",
  "rich",
  "tomli",
  "typer",
  "typing-extensions",
]

[project.optional-dependencies]
dev = [
    "mypy",
    "black",
    "pytest",
    "ruff",
    "types-pyyaml",
]
aws = [
    "boto3",
]

[project.scripts]
phi = "phi.cli.entrypoint:phi_cli"

[project.urls]
homepage = "https://phidata.com"
documentation = "https://docs.phidata.com"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["phidata*", "phi*"]
namespaces = false

[tool.black]
line-length = 120
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/phienv    # exclude phienv directory
  | ^/phidata # exclude phidata directory
)
'''

[tool.ruff]
line-length = 120
exclude = [
  "phienv*",
  "phidata",
]
# Ignore `F401` (import violations) in all `__init__.py` files
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true
exclude = [
  "phienv*",
  "phidata",
]

[[tool.mypy.overrides]]
module = [
  "boto3.*",
  "botocore.*",
  "docker.*",
  "openai.*",
  "pgvector.*",
  "pypdf.*",
  "sqlalchemy.*",
  "setuptools.*",
]
ignore_missing_imports = true
